
version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - gensim_data:/root/gensim-data
    environment:
      - APP_ALLOW_ORIGINS=http://localhost:8080
      - APP_MAX_NEIGHBOURS=40
      - APP_N_CLUSTERS=8
      # Use 1 worker in development for hot reloading compatibility
      - WORKERS=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://backend:8000
    depends_on:
      - backend

volumes:
  gensim_data:
